experiment:
  dataset: yahoo_movies_new
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    side_information:
      - dataloader: KGFlexLoader
        mapping: ../data/{0}/mapping.tsv
#        mapping: ../data/{0}/mapping_clean.tsv
#        mapping: ../data/{0}/mapping_old_KGFlex.tsv
        kg_train: ../data/{0}/all_features_clean.tsv
#        kg_train: ../data/{0}/item_features_old_KGFlex.tsv
       #  second_hop: ../data/{0}/kg_train_2hop.tsv
        properties: ../data/{0}/properties.conf
        additive: True
  prefiltering:
    - strategy: global_threshold
      threshold: 3
  binarize: True
  splitting:
    save_on_disk: True
    save_folder: ../data/{0}/saved_splitting/
    validation_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 50
  gpu: 0
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCGRendle2020, HR, Precision, Recall, ItemCoverage, Gini, SEntropy, ARP]
  models:
    external.KGFlexUmap:
      meta:
        verbose: True
        validation_rate: 1
        save_recs: True
        save_weights: False
        restore: False
        hyper_max_evals: 50
        hyper_opt_alg: tpe
      seed: 42
      lr: 0.005
      epochs: 50
#      batch_size: [32, 64, 128]
      batch_size: [64]
#      embedding: [5, 10, 50]
      embedding: [5]
#      first_order_limit: [10, 50, 100, 200]
      first_order_limit: 200
      second_order_limit: None
      npr: 10
      loader: KGFlexLoader
      early_stopping:
        patience: 4
        monitor: nDCGRendle2020@10
        mode: auto
        verbose: True