experiment:
  dataset: yahoo_movies
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    # test_path: ../data/{0}/test-5core.tsv
    side_information:
      - dataloader: KGFlexLoader
        mapping: ../data/{0}/mapping.tsv
        kg_train: ../data/{0}/kg_train.tsv
        second_hop: ../data/{0}/kg_train_2hop.tsv
        properties: ../data/{0}/properties.conf
        additive: True
  prefiltering:
    - strategy: global_threshold
      threshold: 3
  splitting:
    # save_on_disk: False
    # save_folder: ../data/{0}/5-core/
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 10
  gpu: 0
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10, 5, 3, 1]
    simple_metrics: [nDCGRendle2020, HR, Precision, Recall, ItemCoverage, ARP]
    relevance_threshold: 3
  models:
    external.KGFlexUmap:
      meta:
        verbose: True
        validation_rate: 5
        save_recs: True
        save_weights: False
        restore: False
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      seed: 42
      lr: [loguniform, -7, -4]
      # lr: 0.001
      epochs: 50
      batch_size: [32, 64, 128]
      # batch_size: 128
      embedding: [5, 10, 50]
      # embedding: 256
      first_order_limit: [10, 50, 100, 200]
      second_order_limit: None
      npr: [1, 2, 5, 10]
      loader: KGFlexLoader
