experiment:
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: amazon-book
  top_k: 20
  evaluation:
    cutoffs: [5, 10, 20]
#    simple_metrics: [HR, nDCG, Precision, Recall, EFD, EPC, ItemCoverage, Gini, PopREO, PopRSP, ARP]
    simple_metrics: [Recall]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    Random:
      meta:
        save_recs: False
    MostPop:
      meta:
        verbose: True
        save_recs: False
    external.NGCF:
      meta:
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: True
        validation_metric: Recall
        restore: False
      lr: [0.0001, 0.0005, 0.001, 0.005]
      epochs: 400
      factors: 64
      batch_size: 1024
      l_w: [10e-5, 10e-4, 10e-3, 10e-2, 10e-1, 1, 10, 10e+2]
      weight_size: (64,64,64)
      node_dropout: (0,0,0)
      message_dropout: (0.1,0.1,0.1)
      early_stopping:
        patience: 50
        monitor: Recall@20
        mode: auto
        verbose: True
    external.LightGCN:
      meta:
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: True
        validation_metric: Recall
        restore: False
      lr: 0.001
      epochs: 1000
      factors: 64
      batch_size: 1024
      l_w: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
      n_layers: [1,2,3,4]
      early_stopping:
        patience: 50
        monitor: Recall@20
        mode: auto
        verbose: True